file_format: "1"
id: bleeckeys
name: Bleeckeys
type: shield
url: https://github.com/Bleeck/bleeckeys-module/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - bleeckeys_left
  - bleeckeys_right